# Generated by Django 5.1 on 2024-08-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_delete_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
