# Generated by Django 5.1 on 2024-09-01 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_tags_alter_author_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tags',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
