# Generated by Django 5.1 on 2024-09-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_comic'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='comics', to='myapp.characters'),
        ),
        migrations.AddField(
            model_name='comic',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='comics', to='myapp.groups'),
        ),
        migrations.AddField(
            model_name='comic',
            name='parodies',
            field=models.ManyToManyField(blank=True, related_name='comics', to='myapp.parodies'),
        ),
    ]
