# Generated by Django 5.1 on 2024-09-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_comic_characters_comic_groups_comic_parodies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_picture/'),
        ),
    ]
