# Generated by Django 5.1 on 2024-09-11 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_comic_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='comics', to='myapp.category'),
        ),
    ]
