# Generated by Django 5.1 on 2024-09-21 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_comic_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComicDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_detail', models.ImageField(blank=True, null=True, upload_to='image_detail/')),
                ('page_number', models.IntegerField()),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='myapp.comic')),
            ],
        ),
    ]
