# Generated by Django 5.1 on 2024-09-21 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_comicdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comicdetail',
            old_name='comic',
            new_name='comics',
        ),
    ]
