# Generated by Django 5.1 on 2024-09-21 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_rename_comic_comicdetail_comics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comicdetail',
            name='comics',
        ),
        migrations.AddField(
            model_name='comicdetail',
            name='comic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comic_details', to='myapp.comic'),
        ),
    ]
